lista_preguntas = [
    {'pregunta': '¿Cuál fue la primera consola de videojuegos de la historia?', 'respuesta_1': 'Atari 2600', 'respuesta_2': 'Magnavox Odyssey', 'respuesta_3': 'NES', 'respuesta_correcta': 2},
    {'pregunta': '¿Qué personaje es la mascota oficial de Nintendo?', 'respuesta_1': 'Link', 'respuesta_2': 'Kirby', 'respuesta_3': 'Mario', 'respuesta_correcta': 3},
    {'pregunta': '¿En qué videojuego aparece el personaje Master Chief?', 'respuesta_1': 'Halo', 'respuesta_2': 'Call of Duty', 'respuesta_3': 'Gears of War', 'respuesta_correcta': 1},
    {'pregunta': "¿Qué empresa desarrolla la saga 'The Witcher'?", 'respuesta_1': 'Bethesda', 'respuesta_2': 'CD Projekt Red', 'respuesta_3': 'Ubisoft', 'respuesta_correcta': 2},
    {'pregunta': "¿Cuál es el nombre del protagonista de la serie 'The Legend of Zelda'?", 'respuesta_1': 'Zelda', 'respuesta_2': 'Link', 'respuesta_3': 'Ganondorf', 'respuesta_correcta': 2},
    {'pregunta': "¿En qué año se lanzó el primer juego de 'Super Mario Bros'?", 'respuesta_1': '1985', 'respuesta_2': '1990', 'respuesta_3': '1980', 'respuesta_correcta': 1},
    {'pregunta': '¿Qué videojuego popularizó el género battle royale?', 'respuesta_1': 'Fortnite', 'respuesta_2': 'PUBG', 'respuesta_3': 'Call of Duty: Warzone', 'respuesta_correcta': 2},
    {'pregunta': "¿Qué empresa es la creadora de 'League of Legends'?", 'respuesta_1': 'Blizzard', 'respuesta_2': 'Valve', 'respuesta_3': 'Riot Games', 'respuesta_correcta': 3},
    {'pregunta': '¿Cuál es el título del juego en el que eres un granjero y mejoras tu granja?', 'respuesta_1': 'Stardew Valley', 'respuesta_2': 'Terraria', 'respuesta_3': 'Harvest Moon', 'respuesta_correcta': 1},
    {'pregunta': '¿Qué consola lanzó Sony en 1994?', 'respuesta_1': 'PlayStation', 'respuesta_2': 'PlayStation 2', 'respuesta_3': 'PSP', 'respuesta_correcta': 1},
    {'pregunta': "¿Cómo se llama el personaje principal de 'God of War'?", 'respuesta_1': 'Kratos', 'respuesta_2': 'Ares', 'respuesta_3': 'Hades', 'respuesta_correcta': 1},
    {'pregunta': '¿En qué videojuego cazas monstruos y recolectas materiales?', 'respuesta_1': 'Monster Hunter', 'respuesta_2': 'Dark Souls', 'respuesta_3': 'Diablo', 'respuesta_correcta': 1},
    {'pregunta': "¿Qué videojuego fue conocido por su dificultad y frase 'You Died'?", 'respuesta_1': 'Sekiro', 'respuesta_2': 'Dark Souls', 'respuesta_3': 'Bloodborne', 'respuesta_correcta': 2},
    {'pregunta': "¿Cuál es el objetivo principal en 'Minecraft'?", 'respuesta_1': 'Vencer al Dragón del Fin', 'respuesta_2': 'Construir', 'respuesta_3': 'Sobrevivir', 'respuesta_correcta': 3},
    {'pregunta': '¿Qué juego es conocido por sus impostores y tareas en una nave?', 'respuesta_1': 'Among Us', 'respuesta_2': 'Fall Guys', 'respuesta_3': 'Rust', 'respuesta_correcta': 1},
    {'pregunta': '¿Cuál es el juego de fútbol más popular desarrollado por EA Sports?', 'respuesta_1': 'PES', 'respuesta_2': 'FIFA', 'respuesta_3': 'Football Manager', 'respuesta_correcta': 2},
    {'pregunta': '¿En qué saga aparece el personaje Solid Snake?', 'respuesta_1': 'Metal Gear', 'respuesta_2': 'Call of Duty', 'respuesta_3': 'Splinter Cell', 'respuesta_correcta': 1},
    {'pregunta': "¿Qué personaje es famoso por su grito 'Hadouken'?", 'respuesta_1': 'Ryu', 'respuesta_2': 'Ken', 'respuesta_3': 'Akuma', 'respuesta_correcta': 1},
    {'pregunta': "¿Qué empresa desarrolló el juego 'Overwatch'?", 'respuesta_1': 'Valve', 'respuesta_2': 'Blizzard', 'respuesta_3': 'Epic Games', 'respuesta_correcta': 2},
    {'pregunta': '¿Qué juego combina el género sandbox con supervivencia?', 'respuesta_1': 'Rust', 'respuesta_2': 'Ark', 'respuesta_3': 'Ambos', 'respuesta_correcta': 3},
    {'pregunta': '¿Cuál es el nombre del juego de Valve sobre zombis cooperativo?', 'respuesta_1': 'Left 4 Dead', 'respuesta_2': 'Dying Light', 'respuesta_3': 'Resident Evil', 'respuesta_correcta': 1},
    {'pregunta': '¿En qué juego debes cazar fantasmas con un aspirador?', 'respuesta_1': 'Ghostbusters', 'respuesta_2': "Luigi's Mansion", 'respuesta_3': 'Phasmophobia', 'respuesta_correcta': 2},
    {'pregunta': '¿Qué saga de videojuegos está basada en libros de Andrzej Sapkowski?', 'respuesta_1': 'Skyrim', 'respuesta_2': 'The Witcher', 'respuesta_3': 'Dragon Age', 'respuesta_correcta': 2},
    {'pregunta': '¿Qué saga RPG es desarrollada por BioWare?', 'respuesta_1': 'Mass Effect', 'respuesta_2': 'Final Fantasy', 'respuesta_3': 'Persona', 'respuesta_correcta': 1},
    {'pregunta': '¿Qué consola compite directamente con PlayStation y Xbox?', 'respuesta_1': 'Steam Deck', 'respuesta_2': 'Nintendo Switch', 'respuesta_3': 'Stadia', 'respuesta_correcta': 2},
    {'pregunta': "¿Cuál es el nombre de la IA antagonista en 'Portal'?", 'respuesta_1': 'GLaDOS', 'respuesta_2': 'Cortana', 'respuesta_3': 'EVA', 'respuesta_correcta': 1},
    {'pregunta': '¿Qué juego indie es conocido por su dificultad y estética retro?', 'respuesta_1': 'Cuphead', 'respuesta_2': 'Hollow Knight', 'respuesta_3': 'Ambos', 'respuesta_correcta': 3},
    {'pregunta': '¿Qué juego fue un éxito móvil con caramelos y niveles?', 'respuesta_1': 'Candy Crush', 'respuesta_2': 'Clash of Clans', 'respuesta_3': 'Subway Surfers', 'respuesta_correcta': 1},
    {'pregunta': "¿Cuál es el nombre de la arena de batalla en 'LoL'?", 'respuesta_1': 'Campo de la Justicia', 'respuesta_2': 'Summoner’s Rift', 'respuesta_3': 'Nexus Arena', 'respuesta_correcta': 2},
    {'pregunta': '¿Cuál es la saga de terror con cámaras de seguridad y animatrónicos?', 'respuesta_1': "Five Nights at Freddy's", 'respuesta_2': 'Silent Hill', 'respuesta_3': 'Resident Evil', 'respuesta_correcta': 1},
    {'pregunta': '¿Qué juego tiene como protagonista a un encapuchado asesino?', 'respuesta_1': 'Hitman', 'respuesta_2': "Assassin's Creed", 'respuesta_3': 'Dishonored', 'respuesta_correcta': 2},
    {'pregunta': '¿En qué juego exploras un mundo nórdico con un hacha mágica?', 'respuesta_1': 'Skyrim', 'respuesta_2': 'God of War (2018)', 'respuesta_3': 'Valheim', 'respuesta_correcta': 2},
    {'pregunta': "¿Cuál es el objetivo en 'Tetris'?", 'respuesta_1': 'Construir una torre', 'respuesta_2': 'Evitar que se llene la pantalla', 'respuesta_3': 'Romper bloques de colores', 'respuesta_correcta': 2},
    {'pregunta': '¿Qué personaje de Nintendo es rosa y puede volar?', 'respuesta_1': 'Jigglypuff', 'respuesta_2': 'Kirby', 'respuesta_3': 'Toad', 'respuesta_correcta': 2},
    {'pregunta': '¿Qué consola usaba cartuchos de 64 bits?', 'respuesta_1': 'Sega Genesis', 'respuesta_2': 'PlayStation', 'respuesta_3': 'Nintendo 64', 'respuesta_correcta': 3},
    {'pregunta': "¿Cuál es el nombre del mundo donde ocurre 'Skyrim'?", 'respuesta_1': 'Tamriel', 'respuesta_2': 'Skellige', 'respuesta_3': 'Hyrule', 'respuesta_correcta': 1},
    {'pregunta': '¿Qué juego popularizó la construcción rápida y peleas estilo cartoon?', 'respuesta_1': 'Fortnite', 'respuesta_2': 'Minecraft', 'respuesta_3': 'Apex Legends', 'respuesta_correcta': 1},
    {'pregunta': '¿Qué videojuego consiste en atrapar criaturas con Poké Balls?', 'respuesta_1': 'Digimon', 'respuesta_2': 'Yu-Gi-Oh', 'respuesta_3': 'Pokémon', 'respuesta_correcta': 3},
    {'pregunta': '¿Qué personaje lleva un sombrero rojo y bigote?', 'respuesta_1': 'Luigi', 'respuesta_2': 'Mario', 'respuesta_3': 'Wario', 'respuesta_correcta': 2},
    {'pregunta': "¿Qué empresa desarrolló la saga 'Final Fantasy'?", 'respuesta_1': 'Capcom', 'respuesta_2': 'Square Enix', 'respuesta_3': 'Koei Tecmo', 'respuesta_correcta': 2},
    {'pregunta': "¿Qué tipo de juego es 'Counter-Strike'?", 'respuesta_1': 'MOBA', 'respuesta_2': 'RPG', 'respuesta_3': 'FPS', 'respuesta_correcta': 3},
    {'pregunta': '¿Qué juego tiene un modo historia sobre un padre y su hijo?', 'respuesta_1': 'God of War', 'respuesta_2': 'Red Dead Redemption 2', 'respuesta_3': 'Gears 5', 'respuesta_correcta': 1},
    {'pregunta': '¿Cuál fue uno de los primeros juegos de disparos en 3D?', 'respuesta_1': 'Doom', 'respuesta_2': 'Wolfenstein 3D', 'respuesta_3': 'Quake', 'respuesta_correcta': 2},
    {'pregunta': "¿Qué compañía desarrolló el juego 'Genshin Impact'?", 'respuesta_1': 'miHoYo', 'respuesta_2': 'NetEase', 'respuesta_3': 'Tencent', 'respuesta_correcta': 1},
    {'pregunta': '¿Cuál es el nombre del auto en Rocket League?', 'respuesta_1': 'Octane', 'respuesta_2': 'Turbo', 'respuesta_3': 'Fennec', 'respuesta_correcta': 1},
    {'pregunta': '¿Qué juego simula un parque de dinosaurios?', 'respuesta_1': 'Jurassic World Evolution', 'respuesta_2': 'Zoo Tycoon', 'respuesta_3': 'The Isle', 'respuesta_correcta': 1},
    {'pregunta': '¿Qué saga de terror usa una linterna como mecánica principal?', 'respuesta_1': 'Alan Wake', 'respuesta_2': 'Resident Evil', 'respuesta_3': 'Dead Space', 'respuesta_correcta': 1},
    {'pregunta': "¿Qué personaje de Mortal Kombat lanza un arpón y grita '¡Ven aquí!'?", 'respuesta_1': 'Sub-Zero', 'respuesta_2': 'Scorpion', 'respuesta_3': 'Raiden', 'respuesta_correcta': 2},
    {'pregunta': '¿Qué famoso juego de Rockstar está ambientado en el Viejo Oeste?', 'respuesta_1': 'L.A. Noire', 'respuesta_2': 'Red Dead Redemption', 'respuesta_3': 'GTA', 'respuesta_correcta': 2},
]